spring:
  server:
    port: 8080
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    password: dobotest321
    url: jdbc:oracle:thin:@10.1.180.198:1521/wbmtest
    username: dobo
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 0
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**

logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/nmyslog/nmys


